### ISSUE TITLE
Glyphs quality

### ISSUE THREAD

**Issue by beibean** [littlevgl/lv_font_conv#15] opened 2019-07-11 07:10 UTC
Hi @puzrin,

First of all, congratulations for the great job done with de font converter 😉.

I was migrating from LittlevGL v5.3 to LittlevGL v6.0 and found some issues discussed [here](https://forum.littlevgl.com/t/changes-found-on-new-font-converter/187).

I already understood more or less the stuff related with new paradigma. Whichever, the thing I am worry about is the quality of the glyphs with new font converter. 

As I show [in this post](https://forum.littlevgl.com/t/changes-found-on-new-font-converter/187/7?u=beibean), there is a bit lost in glyph quality. I guess is not about the new font converter at all but for the method of getting the .ttf into image.

What do you think? It might be an special case, but is important on my project.

Do you know  if is there any possibility to use the method used in LittlevGL v5.3 just for getting the glyphs images?

Thanks in advance

**Comment by puzrin** [comment] 2019-07-11 13:01
Size can be a bit different, because new version calculate metrics exactly as is should.

Discussion of "render any TTF into OLED with any size and best quality" can be endless, because technically impossible. Instead, i'd suggest you to describe exactly what you really need (list of sizes, bpp, font family, ...) and we will try to find solution.

About missed `_` - use `--dump` to check source chars. This may be problem not with font but with renderer.

> Do you know if is there any possibility to use the method used in LittlevGL v5.3 just for getting the glyphs images?

Only if you rewrite convertor back to PHP and use built-in renderer :)

**Comment by kisvegabor** [comment] 2019-07-11 13:12
The PHP version uses FreeType to render the fonts. Is it ported to JS too? If so, it might be worth a try.

**Comment by puzrin** [comment] 2019-07-11 14:21
> The PHP version uses FreeType to render the fonts.

1. Nobody knows real options used. For example, hinting on/off. There may be difference between "readability" and "smoothness".
2. Prior to use FreeType, php script calculated desired metrics (scale, for example), and it was far from perfect.

> Is it ported to JS too? If so, it might be worth a try.

I declined use of native FreeType, because installation difficulties would make package not useable for end customers. JS renderer, used here is well known `opentype.js`, it's good enougth.

**Comment by kisvegabor** [comment] 2019-07-12 05:22
> I declined use of native FreeType, because installation difficulties would make package not useable for end customers. JS renderer, used here is well known opentype.js, it's good enougth.

So there no reasonable way to improve quality?

**Comment by puzrin** [comment] 2019-07-12 11:46
> So there no reasonable way to improve quality?

In general, problem of ideal write of ANY vector font to low resolution display has no technical solution. I'd say, proper font selection for specific size will give much better effect.

Attempt to drop hinting will be waste of time IMO. With some luck, you will exchange one problem to another - bold lines to blured contours.

I got no answer about `_`. That may be some bug about cropping line bottom (but i hope not in font). Anyway, all this need a sample repo with reproducible samples and comments where to look. Inspecting with `--dump` will quickly show all defects.

It may be possible to improve horisontal resolution 3x via subpixel smoothing, but i did not digged deep into. IMO spends in this direction are not reasonable (just use HiDPI display instead with much better effect).

**Comment by kisvegabor** [comment] 2019-07-12 13:44
Using (or at least trying) FreeType is really not possible direction?

> Attempt to drop hinting will be waste of time IMO. With some luck, you will exchange one problem to another - bold lines to blured contours.

What does hinting mean in this context? Could explain it or link something to read?

> IMO spends in this direction are not reasonable (just use HiDPI display instead with much better result).

Anyway, better quality is better. :slightly_smiling_face: 
It would be nice to achieve the quality of the PHP converter. It really used some scaling and other tricks but these were only to modify the font size. So there were no hacks on the rendering itself.

**Comment by puzrin** [comment] 2019-07-12 14:14
> Using (or at least trying) FreeType is really not possible direction?

Everything possible. And full rewrite to php possible too. But without me :)

> What does hinting mean in this context? Could explain it or link something to read?

https://www.freetype.org/ttfautohint/ - see intro & docs. That's corrections for small sizes to improve visual quality

> It would be nice to achieve the quality of the PHP converter. It really used some scaling and other tricks but these were only to modify the font size. So there were no hacks on the rendering itself.

It would be nice to have test repo with reproducible samples first, prior to discuss anything. Convertor has `--dump` mode, and it's easy to check what it writes to font file.

If anyone wish to check hinting difference, hinting can be disabled [here](https://github.com/littlevgl/lv_font_conv/blob/34ad2025113fc82995dcb6b8b8e44ee70588b41e/lib/collect_font_data.js#L130) in option.

**Comment by embeddedt** [comment] 2019-07-12 15:46
> (just use HiDPI display instead with much better result)

We can't expect all embedded systems to have HiDPI displays.

**Comment by puzrin** [comment] 2019-07-12 16:38
I this our problem we need spend time to discuss? Problem is trivial - author need to create test repo with font file, and put into readme list of minimal CLI commands to reproduce results.

**Comment by puzrin** [comment] 2019-07-13 15:05
I did dump P of roboto and some freesans from internet with this command (set appropriate font path):

```
$ ./lv_font_conv.js --size 14 --bpp 4 --format dump --font ./node_modules/roboto-fontface/fonts/roboto/Roboto-Regular.woff --symbols P -o 1111
```

![Снимок экрана от 2019-07-13 17-34-47](https://user-images.githubusercontent.com/319465/61172971-10148080-a595-11e9-9428-5318d8eb7f7c.png)
![Снимок экрана от 2019-07-13 17-35-56](https://user-images.githubusercontent.com/319465/61172972-10148080-a595-11e9-953c-ec4560a38a6b.png)

Effect is caused by location of vertical line between pixels (as a result, in freesans it's more gray).

Could not find difference with and without hinting, and it's strange. Tried to enforce hinting via `ttfautohint` tool, but renderer crashed with error

```
$ ./lv_font_conv.js --size 14 --bpp 4 --format dump --font freesans_ttfa_hinted.ttf --symbols P -o 1111
Hinting error:Error: unknown instruction: 0x78
Note: further hinting errors are silenced
```

Probably, built-in hints are for very small sizes, and freetype may use autohinter for bigger size. Will ask opentype.js guys why renderer crashes.

Anyway, i'd suggest to use pixel-perfect fonts for specific size if you need best quality.

**Comment by puzrin** [comment] 2019-07-13 15:28
Reported https://github.com/opentypejs/opentype.js/issues/395, this should be fixed prior we next attempt.

**Comment by kisvegabor** [comment] 2019-07-15 03:29
>  Reported opentypejs/opentype.js#395, this should be fixed prior next attempt.

Awesome!

**Comment by puzrin** [comment] 2019-07-15 07:01
For info. Seems it should be possible to assemble and use freetype2 via emscripten for use under node.js. But existing state of npm modules is very outdated:

- https://www.npmjs.com/search?q=freetype
- https://www.npmjs.com/search?q=freetype2

Also take into account:

- There are no guarantee of better results
- Freetype has GPL license. That requires keep it in separate package for npm script, and may cause some restrictions for website (where everything assembled into single script)
- I have no time/skills/interest for such investigations. If someone wish to spend time on this - i may try to help about nodejs questions (but nothing concrete).

**Comment by embeddedt** [comment] 2019-07-16 11:58
> Freetype has GPL license.

Are you sure? The website says that it is dual licensed under the FreeType License and the GPL: https://www.freetype.org/license.html

**Comment by puzrin** [comment] 2019-07-16 12:25
@embeddedt you are right. It should not become a fatal problem.

If you find a way to build freetype as node.js lib (with JS-callable API) - kick me to take a look. Webassembly internals would be preferable, but not critical.

In last try i remenber, we did manual wrapper and that looked ugly https://github.com/fontello/wawoff2/blob/master/compress.js. I think, emscripten devs should have something better for us.

**Comment by beibean** [comment] 2019-07-18 05:16
Hi, 

I've been out of the lvgl project, and will go on holidays soon.

I will test in a few weeks with other fonts to see if they are rendered better (roboto is a good candidate) and fit the project and investigate using ```--dump``` as puzrin suggests.

**Comment by puzrin** [comment] 2019-07-24 22:07
No good news about opentype.js. Hinting processor had no support of conditional jumps. Adding this support was trivial, but resulting images become broken. I suspect, there are more bugs in previously implemented parts - fixing those needs completely different spends. 

I would not recommend to wait solution from opentype.js in realistic future. It would be better, if someone could investigate how to build freetype for node.js via emscripten. In this case i could replace renderer.

**Comment by embeddedt** [comment] 2019-07-24 23:19
@puzrin FreeType is already ported to Emscripten. The question is how you want to expose the APIs to `node.js`.

**Comment by puzrin** [comment] 2019-07-24 23:32
@embeddedt Under "build for node.js" i mean providing appropriate API-s.

As far as i understand from doc, emscripten has some support https://emscripten.org/docs/porting/connecting_cpp_and_javascript/embind.html. But i can't understand how is this expected to be initialized? Because as far as i know, init process is async (at least, webassembly init is async and this can't be avoided).

**Comment by embeddedt** [comment] 2019-07-24 23:33
> Because as far as i know, init process is async (at least, webassembly init is async and this can't be avoided).

Right. I think the rest of the font convertor would have to accommodate that.

**Comment by puzrin** [comment] 2019-07-24 23:41
That's not a big problem (i will do), if anyone can create a transpiled freetype package for node.js (if that's technically possible).

Draft will be ok too (build script & info how to init/call from node). I'm ready to help with node-specific details, how to properly arrange & publish package.

**Comment by embeddedt** [comment] 2019-07-24 23:42
> if anyone can create a transpiled freetype package for node.js (if that's technically possible).

Can you explain exactly what the steps would be to create that package, beyond simply including FreeType into an Emscripten program? Would I essentially have to bring out the FreeType APIs to JavaScript?

**Comment by puzrin** [comment] 2019-07-24 23:57
If you have some time, i'd suggest to look at https://github.com/fontello/wawoff2 as [bad] example. Just to be sure that's possible. Problem is, that solution uses manual wrappers & all functions done async to hide init.

As far as i understand, `embind` is intended to generate JS glue automatically. But:

- i never used it
- i could not understand from docs how they expect to initialize runtime.

So, i see this steps:

1. Try to understand, does emscripten really supports compilation to node.js modules & how they expect init to be done
2. Provide makefile or instruction, how to build that (no need to test, just build something "looking like useable from node")
3. From this point i can do all the rest about node (or help if anyone wish to learn it).

**Comment by embeddedt** [comment] 2019-07-25 00:12
It seems possible to create `node.js` modules when compiling to WebAssembly (see the first half of this page): https://developers.google.com/web/updates/2019/01/emscripten-npm

**Comment by puzrin** [comment] 2019-07-25 11:12
Well, as far as i see from [ems faq](https://emscripten.org/docs/getting_started/FAQ.html#how-can-i-tell-when-the-page-is-fully-loaded-and-it-is-safe-to-call-compiled-functions), they suggest promise-like loading interface with `-s MODULARIZE=1`. That's fine.

Also, according to your link, docker should simplify builds.

What is not clear - how to create interface to call freetype2 methods and pass structs OR typed pointers. Google example use primitive types, those are not enough.

**Comment by embeddedt** [comment] 2019-07-25 11:22
@puzrin It would be simplest, IMO, to build the renderer component in C, and create an API that is used by the higher-level components of the font convertor. That way, there would be a very reduced amount of binding code that would need to be written.

> that solution uses manual wrappers

Unfortunately, I think that's unavoidable when trying to bind two very different languages. 

> `embind` is intended to generate JS glue automatically

I'm not so sure about this. It looks like `embind` is intended to generate JS glue when told information about the functions. Look at the super-simple C++ example: https://emscripten.org/docs/porting/connecting_cpp_and_javascript/embind.html#classes

**Comment by puzrin** [comment] 2019-07-25 11:52
Ok. C renderer will be useable too. I think, we could continue use `opentype.js` to work with metrics data, and use FreeType2 only to draw single glyph.

Will you have a time to do such "draft" with build script for docker, useable for `cwrap` call? With some minimal "caching" to not parse font very time for each glyph.

**Comment by embeddedt** [comment] 2019-07-25 11:56
@puzrin I can get it to the point where you can build a module with FreeType and include it in the font convertor. Beyond that, I have little experience with FreeType, so I won't be of much use. I think you (or someone else) will have to write the relevant C routines for that.

**Comment by puzrin** [comment] 2019-07-25 12:00
I'm not strong in C (can do some simple things, when no choice) and not familiar with freetype too. I could try to describe desired C interface, if that helps.

**Comment by kisvegabor** [comment] 2019-07-25 12:04
@puzrin 
IT'd be a good starting point. I'm also not familiar with Freetype but let's see the required interface. Generating the bitmap shouldn't be too complicated.

**Comment by puzrin** [comment] 2019-07-25 12:34
Something like this:

```C
// seems FT can autodetect font type
int create_fontface(Uint8Array font, uint16 size, &fontface_data);

int free_fontface(&fontface_data);

int render_glyph(&fontface_data, uint32 glyph_code, Uint8Array &rgba_buffer, uint32 uint32 buf_size_x, uint32 buf_size_y, uint32 glyph_pos_x, uint32 glyph_pos_y);
```

I think this should be testable without JS at all.

Or, as altermative, without cache (for first attempt):

```C
int render_glyph(Uint8Array font, uint16 size, uint32 glyph_code, Uint8Array &rgba_buffer, uint32 uint32 buf_size_x, uint32 buf_size_y, uint32 glyph_pos_x, uint32 glyph_pos_y);
```

**Comment by kisvegabor** [comment] 2019-07-26 11:28
> I think this should be testable without JS at all.

Sure creating byte array with the rendered image should be that simple. Do you need some assistance with that?

**Comment by puzrin** [comment] 2019-07-26 11:38
> Do you need some assistance with that?

Yes.

- Ideally, it would be nice to get working C code with signature above (second example), and docker file to build. In separate repo or branch. Then i promise to intergate this with JS as soon as possible.
- If that's difficult - without docker file. Only compile-able code + example.

Under example i mean "read font from file, render char `P` and dump result array to console".

**Comment by kisvegabor** [comment] 2019-07-26 12:44
I've followed [this tutorial](https://www.freetype.org/freetype2/docs/tutorial/step1.html) and made it work without Docker.

[freetype_test.zip](https://github.com/littlevgl/lv_font_conv/files/3435757/freetype_test.zip)

Steps:
- Download Freetype from [here](https://sourceforge.net/projects/freetype/files/)
- `make`
- `sudo make install`
- In `freetype_test`: ` gcc render.c -I/usr/include/freetype2 -L/usr/local/lib -lfreetype`

**Comment by puzrin** [comment] 2019-07-26 13:05
Thank you! Could you do this changes:

- Move code to separate function, to make sure signature does not diverge too much from https://github.com/littlevgl/lv_font_conv/issues/15#issuecomment-515025315. It will help a lot, if i could copy-paste code, without thinking on C.
- In your example, `FT_New_Face` loads code from file, that's not available in JS/Web. As described in signature, file data should be loaded from memory (i guess, some form of array, probably with length in separate param). I mean, `main` should load file, call renderer and then dump result.

**Comment by kisvegabor** [comment] 2019-07-26 16:19
I've created a git repo for it and updated with requested changes:
https://github.com/kisvegabor/freetype_test

**Comment by puzrin** [comment] 2019-07-26 16:24
Thanks a lot. Give me several days to setup build scripts (never used docker before), then will try to use FT as backend. That should not take too much time, i'll keep you informed on progress.

**Comment by kisvegabor** [comment] 2019-07-26 16:41
Great, thank you!

**Comment by kisvegabor** [comment] 2019-08-14 09:36
@puzrin 
Is there any news with FreeType?

**Comment by puzrin** [comment] 2019-08-14 10:15
Not yet, sorry. Have to do other projects. But i remember about this issue.

**Comment by kisvegabor** [comment] 2019-08-14 14:07
Ok, thank you for the feedback.

**Comment by puzrin** [comment] 2019-09-03 10:52
I've tagged last stable version and commited API rewrite to be async https://github.com/littlevgl/lv_font_conv/commit/6bd7c74b18d76a15e973ed0a35c5c28b50b05f6b

That does not add "new features", but allows to call async init for emscripten-compiled libraries.

**Comment by puzrin** [comment] 2019-09-11 17:44
@kisvegabor, @embeddedt  

There are some progress (see branches). Need help with freetype lib build. Current one (default) does NOT support woff/woff2 (ttf is ok). Here is [Dockerfile](
https://github.com/littlevgl/lv_font_conv/blob/freetype/support/Dockerfile)

Could you help with improving this? I mean:

- Make sure all mandatory options (autohinting, woff/woff2) are enabled
- Disable unused options to reduce build size.

To run via npm:

```sh
# build docker image, with emscripten & precompiled freetype
npm run build:dockerimage

# compile renderer glue for js (run shell file in our docker image)
npm run build:freetype
```

Probably need extra libs, more options & better paths instead of `emmake make install` in docker config.

**Comment by puzrin** [comment] 2019-09-11 22:31
Note, woff (not woff2) is "ttf + gzip". Probably, freetype was misconfigured somehow. I have no ideas why woff loading can fail, except decompression problems. From the other hand, FreeType has built-in zlib and i don't know why this may fail.

**Comment by kisvegabor** [comment] 2019-09-13 14:51
I've tryied and it work well expect a minor issue in the writer. The header of the font looked like this:
```c

#ifndef LV_FONT_ROBOTO_16
#define LV_FONT_ROBOTO_16 1
#endif

#if undefined
```

On the left is the old version, on the right there is the new. They seem quite the same for me.

![image](https://user-images.githubusercontent.com/7599318/64871925-86da0280-d646-11e9-8089-27d679cf2768.png)

**Comment by puzrin** [comment] 2019-09-13 15:34
If you have time - try 1bpp & 4bpp FreeSans, difference should be visible. On current screenshot i don't see difference at all. Are sources really different?

Please, report all found bugs in #23.

**Comment by kisvegabor** [comment] 2019-09-13 16:53
Ups, my bad. 

The new version is where the cursor on to the top of the list and the text are longer. The new version looks sharper. See the `t` and `T` letters.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/7599318/64879933-5fd7fc80-d657-11e9-856b-aae5e00d3029.gif)

### New
![1](https://user-images.githubusercontent.com/7599318/64880074-a3326b00-d657-11e9-9772-86b9a497ca2f.png)

### Old
![2](https://user-images.githubusercontent.com/7599318/64880076-a3cb0180-d657-11e9-92c7-371a93023496.png)

**Comment by puzrin** [comment] 2019-09-13 17:01
Yes, that's one of hinting method - it slightly change glyphs to fit more points into display pixels.

If someone don't like that, can add option to disable.

**Comment by puzrin** [comment] 2019-09-13 17:07
It's strange - text width changed. Not sure is this correct or not.

**Comment by puzrin** [comment] 2019-09-13 17:19
Try to create font without kerning. Seems it's missed (not used) in hinted sample.

**Comment by kisvegabor** [comment] 2019-09-13 17:47
Disabling the kerning was no effect. I visually compared the kerning tables and they looked the same.

However, there are differences in the `glyph dsc` table:
### Old 
```c
  {.bitmap_index = 0, .adv_w = 0, .box_h = 0, .box_w = 0, .ofs_x = 0, .ofs_y = 0} /* id = 0 reserved */,
    {.bitmap_index = 0, .adv_w = 63, .box_h = 0, .box_w = 0, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 0, .adv_w = 66, .box_h = 13, .box_w = 2, .ofs_x = 1, .ofs_y = -1},
    {.bitmap_index = 12, .adv_w = 82, .box_h = 4, .box_w = 4, .ofs_x = 1, .ofs_y = 8},
    {.bitmap_index = 21, .adv_w = 159, .box_h = 12, .box_w = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 80, .adv_w = 144, .box_h = 16, .box_w = 9, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 148, .adv_w = 188, .box_h = 13, .box_w = 12, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 218, .adv_w = 159, .box_h = 13, .box_w = 10, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 280, .adv_w = 45, .box_h = 4, .box_w = 2, .ofs_x = 0, .ofs_y = 8},
```

### New
```c
  {.bitmap_index = 0, .adv_w = 0, .box_h = 0, .box_w = 0, .ofs_x = 0, .ofs_y = 0} /* id = 0 reserved */,
    {.bitmap_index = 0, .adv_w = 64, .box_h = 0, .box_w = 0, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 0, .adv_w = 80, .box_h = 12, .box_w = 3, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 10, .adv_w = 80, .box_h = 4, .box_w = 5, .ofs_x = 0, .ofs_y = 8},
    {.bitmap_index = 21, .adv_w = 176, .box_h = 12, .box_w = 9, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 75, .adv_w = 144, .box_h = 15, .box_w = 9, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 141, .adv_w = 192, .box_h = 12, .box_w = 12, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 205, .adv_w = 160, .box_h = 12, .box_w = 10, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 260, .adv_w = 48, .box_h = 4, .box_w = 3, .ofs_x = 0, .ofs_y = 8},
```

E.g. in the last line `box_w = 2` has changed to `box_w = 3` bur `ofs_x` remained 0.

**Comment by puzrin** [comment] 2019-09-13 18:29
https://github.com/littlevgl/lv_font_conv/commit/1667bcd132bbf3ad575136dc8fea831c74587ee6

Fixed (i hope) hinting flags. Try update please.

**Monochrome (1bpp)**

Now monochrome hinter is really used. Dump looks really good. I'm satisfied.

**Others (2bpp+)**

Switched to less aggressive hinter (FT_LOAD_TARGET_LIGHT). It adds only horizontal improvements, and doesn't touch vertical lines. As a result -  kerning space not affected.

Difference is small for Roboto, but notable for FreeSans.

Using more aggressive hinting (FT_LOAD_TARGET_NORMAL) requires harfbuzz to compensate distortion. I'd say, current settings should be good enougth.

**Comment by puzrin** [comment] 2019-09-14 06:26
@kisvegabor 

https://github.com/littlevgl/lv_font_conv/issues/15#issuecomment-531268361

I could not reproduce this bug with undefined. Tried both CLI and `npm start`. Got there "font name" as expected.

Starting to fix missed property with compression ID.

**Comment by kisvegabor** [comment] 2019-09-14 07:31
Great! Now the text has quite the same length. However, I've noticed that the `rt` in "Char" has no letter space. It's not the kerning because it's the same with disabled kerning.

![image](https://user-images.githubusercontent.com/7599318/64904971-d7e30880-d6d1-11e9-9b3d-fe130574f563.png)


> I could not reproduce this bug with undefined. Tried both CLI and npm start. Got there "font name" as expected. If it still exists - need info how to reproduce.

Sorry, I didn't mention, it's ok now. git was tricked me. :)

**Comment by puzrin** [comment] 2019-09-14 07:45
> However, I've noticed that the rt in "Char" has no letter space. It's not the kerning because it's the same with disabled kerning.

Is this a problem we should solve? For example `tt` on `Button` are also close, and that's normal. We should care not about "pixels" but about readability.

Technically, if you wish to experiment with disabled hinting at all, you can comment [here](https://github.com/littlevgl/lv_font_conv/blob/dev/lib/freetype/index.js#L175-L178) first line and `else` block (may be first one will be enougth). But IMHO current light hinting should be always better than without.

**Comment by kisvegabor** [comment] 2019-09-14 08:08
IMO such spacing issues looks ugly and unexpected but probably what we gain with hinting is more than we lose on spacing.

**Comment by puzrin** [comment] 2019-09-14 09:23
That may be subjective, but i don't reject adding CLI flags to tune hinting if anyone interested.

At current moment, i have no ideas what else can be changed or improved in convertor. It can be released, if no sudden bugs found. It would be nice to get "C" help with rest of tasks in #23, but those are not critical for release.

I think, current issue can be closed.

**Comment by kisvegabor** [comment] 2019-09-14 09:30
> That may be subjective, but i don't reject adding CLI flags to tune hinting if anyone interested.

It sounds good to allow people to fine-tune the hinting if needed. 

>  It would be nice to get "C" help with rest of tasks in #23, but those are not critical for release.

I think I can't do them better than you. :)

If the hinting flags are added, I agree that the new version can be released.

**Comment by puzrin** [comment] 2019-09-14 09:51
> I think I can't do them better than you. :)

Yeah, my C looks like your JS :)

> If the hinting flags are added, I agree that the new version can be released.

Could you describe exactly, which flags needed? Or even better - provide desired combinations of flags for [FT_Load_Glyph](https://github.com/littlevgl/lv_font_conv/blob/dev/lib/freetype/index.js#L181) call?

At first glance, there are this possibilities:

- Disable autohinting.
- Disable autohinting AND built-in hinting instructions from font file.
- Force more aggressive autohinting.

But i'm not sure all those are really needed, and don't like garbage options just for abstract "freedom". IMO option `--no-autohinting` could be enought, and only if anyone says he really need it.

**Comment by puzrin** [comment] 2019-09-14 14:25
After thinking a bit, seems autohinting control should be on font-level, not global.

- With high probability, nobody disable it on text fonts
- May be, it will be useful to disable on iconic font, because those have no text glyphs to fetch basic sizes
- May be, someone may wish to use strong autohinter with icons, because those have no kerning and related defects are impossible.

So, 2 options, per font:

- `--autohint-off`
- `--autohint-strong`

**Comment by puzrin** [comment] 2019-09-14 17:09
https://github.com/littlevgl/lv_font_conv/commit/9062e52f8a5d45b8a43c112648495f96758120c8

Added autohinting control option. With low probability may be useful for iconic fonts.

Seems only intensive testing needed for convertor release.

**Comment by embeddedt** [comment] 2019-09-14 23:33
> It would be very nice is someone more experienced could help with emscripten. FreeType build issue does not depend on JS at all.

@puzrin It sounds like you've made some changes since you wrote that comment. What still needs to be done?

**Comment by puzrin** [comment] 2019-09-15 00:33
@embeddedt 

- Make FreeType build exactly as in ports
  - now zlib compiled via kludge & harfbuzz missed at all
- Fix include & lib paths to freetype. Now use `make install`, and that place wasm files to system folder. It would be better to keep those in `/opt/...` or something similar.

**Comment by puzrin** [comment] 2019-09-17 14:19
Any news? Should we keep this issue open? Can i merge dev into master for more intensive use?

**Comment by embeddedt** [comment] 2019-09-17 14:22
> Any news?

I've begun working on it locally but I haven't pushed anything yet.

> Should we keep this issue open?

I think it can be closed. We can use #23 for tracking improvements to the Docker image.

> Can i merge dev into master for more intensive use?

Since it builds properly now and works I think it should be safe to merge it into `master`, provided that compression is disabled by default (since LittlevGL 6.0 doesn't support it).

**Closed** 2019-09-17 14:30 UTC

**Comment by puzrin** [comment] 2019-09-17 14:31
> provided that compression is disabled by default (since LittlevGL 6.0 doesn't support it).

It was always enabled by default (in previous version too)

**Comment by puzrin** [comment] 2019-09-17 14:35
merged `dev` to `master`
